name: Deploy MemoryGym (Optimizado)
on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io

jobs:
  # 1. Compilation and image upload to GitHub Container Registry
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image_name: ${{ steps.string.outputs.lowercase }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Convert repository name to lowercase
        id: string
        run: |
          echo "lowercase=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ steps.string.outputs.lowercase }}:latest

  # 2. Deploy
  deploy-vps:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Copy Docker Compose to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: "~/apps/memorygym"

      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/apps/memorygym
            docker compose pull
            docker compose up -d